// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvrnJJmblFgVlhlbfzgsTq0rX2zpXpydQ',
    appId: '1:349587396824:web:abd1a1fd1d32115f199fad',
    messagingSenderId: '349587396824',
    projectId: 'expensetracker-ff497',
    authDomain: 'expensetracker-ff497.firebaseapp.com',
    storageBucket: 'expensetracker-ff497.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKs5K8CbwDghLzaxo6eosmhnIt3BEd3m8',
    appId: '1:349587396824:android:0e74a1a8e468bb35199fad',
    messagingSenderId: '349587396824',
    projectId: 'expensetracker-ff497',
    storageBucket: 'expensetracker-ff497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt72U-GAVprG7oJ3Q8933TvSJ3wDVm8Lg',
    appId: '1:349587396824:ios:744a2f626f06968a199fad',
    messagingSenderId: '349587396824',
    projectId: 'expensetracker-ff497',
    storageBucket: 'expensetracker-ff497.firebasestorage.app',
    iosBundleId: 'com.example.expenceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt72U-GAVprG7oJ3Q8933TvSJ3wDVm8Lg',
    appId: '1:349587396824:ios:744a2f626f06968a199fad',
    messagingSenderId: '349587396824',
    projectId: 'expensetracker-ff497',
    storageBucket: 'expensetracker-ff497.firebasestorage.app',
    iosBundleId: 'com.example.expenceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvrnJJmblFgVlhlbfzgsTq0rX2zpXpydQ',
    appId: '1:349587396824:web:a41e3255c0d86732199fad',
    messagingSenderId: '349587396824',
    projectId: 'expensetracker-ff497',
    authDomain: 'expensetracker-ff497.firebaseapp.com',
    storageBucket: 'expensetracker-ff497.firebasestorage.app',
  );
}
